### PR TITLE
Registration token

### PR DESCRIPTION
**Pull request by chingor13**
We need to get a registration token to be able to register hosts to the environment we just created.

### CODE REVIEW

**Comment by chingor13** [comment]
I need to fix the tests, but does this seem reasonable? It waits until the project is ready and waits until the registration token is ready by fetching the "self" link until it's no longer in the "registering" state.

**Comment by dplummer** [comment]
Yea, seems good. Is registration token for adding a host?

**Comment by chingor13** [comment]
Yeah you need it to register a host. It's different from deploy/api access keys.

**Comment by chingor13** [comment]
@dplummer this is ready for review

**Comment by dplummer** [comment]
Released as version 0.3

**Pull request merged**
